### ISSUE TITLE
Two fingers on the carousel image cause an issue

### ISSUE THREAD

**Issue by Ahmedhk** [serenader2014/flutter_carousel_slider#166]
**Good Day,

First of all thank you so much for this amazing widget, the only issue i'm facing with it is when i touch the carousel images with two fingers at the same time the carousel freezes & i get the following error:-**

I/flutter (17475): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17475): The following assertion was thrown while dispatching a pointer event:
I/flutter (17475): 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 377 pos 12: '_initialButtons ==
I/flutter (17475): kPrimaryButton': is not true.
I/flutter (17475):
I/flutter (17475): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17475): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17475): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17475):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17475):
I/flutter (17475): When the exception was thrown, this was the stack:
I/flutter (17475): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:377:12)
I/flutter (17475): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:308:7)
I/flutter (17475): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (17475): #5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter (17475): #6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (17475): #7      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (17475): #8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (17475): #9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (17475): #13     _invoke1 (dart:ui/hooks.dart:275:10)
I/flutter (17475): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
I/flutter (17475): (elided 5 frames from class _AssertionError and dart:async)
I/flutter (17475):
I/flutter (17475): Event:
I/flutter (17475):   PointerUpEvent#af6a7(position: Offset(150.8, 236.8))
I/flutter (17475): Target:
I/flutter (17475):   <WidgetsFlutterBinding>
I/flutter (17475): ════════════════════════════════════════════════════════════════════════════════════════════════════

**below is my sample code:-**

import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';

class Account extends StatefulWidget {
  final List<String> imgList = [
  // 'https://iwebp.de/images/10-used-car-online-tips-orig7167c02a645ae3c8.jpg',
  'https://miro.medium.com/max/681/0*TWwRFwyw23Qx61ah',
  'https://www.nairaland.com/attachments/4672013_20161229105101_jpeg48bfab529119573d664e724f440c1ba8',
  'https://merkandi.com/images/offer/6s-8-1569484391-1569485452.jpg',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSoy0zUzmtIimR9oIwcL49r1Lj7695tLvdZ2ouUAkbxHWUAFhSh&usqp=CAU',
  'https://s3-us-west-1.amazonaws.com/contentlab.studiod/getty/cache.gettyimages.com/bb5929bc010148979789ecb2e018df14.jpg',
  'https://sc01.alicdn.com/kf/Udd63d4b97444472b80162c569147eadeR.jpg',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT25hCTF55j0BE2hgP-zfbOllzcVpCg5AryZF-hmuGmdIa-C_uY&usqp=CAU',
  'https://invimg.autofunds.net/InventoryImages/2019/12/18/2478_1566346_SC1_9324250_10425118422019_90.jpg',
  'https://www.expat.com/upload/classifieds/medium/1561654811-2856-full_size-t1561654811.jpg',
];
  @override
  _AccountState createState() => _AccountState();
}

class _AccountState extends State<Account> {
  int _current = 0;
  @override
  Widget build(BuildContext context) {
    return CarouselSlider(
      items: widget.imgList.map((item) => Container(
        child: Image.network(item, fit: BoxFit.cover, width: 1000.0),
      )).toList(),
      options: CarouselOptions(
        // autoPlay: false,
        // enableInfiniteScroll: false,
        // enlargeCenterPage: false,
        // viewportFraction: 1,
        
        // // enlargeCenterPage: true,
        // aspectRatio: 1.0,
        onPageChanged: (index, reason) {
          setState(() {
            _current = index;
          });
        },
      ),
    );
  }
}

**Comment by yourshinsuke** [comment]
yes
Fix it!

**Comment by yourshinsuke** [comment]
https://stackoverflow.com/questions/62689343/carousel-slider-error-on-multiple-finger-tap-failed-assertion-line-377-pos-12

**Comment by yourshinsuke** [comment]
@Ahmedhk 
I replaced other one.

`flutter_carousel_slider: ^1.0.1`

it doesn't have many features, but not bug like it.
