### ISSUE TITLE
carousel_slider Error on Multiple Finger Tap : Failed assertion: line 377 pos 12: '_initialButtons == kPrimaryButton': is not true

### ISSUE THREAD

**Issue by adhikaar** [serenader2014/flutter_carousel_slider#173]
ISSUE:
-------
In carousel_slider, tapping simultaneously with more than one finer causes the Gesture Detector to crash and become non-responsive.

ERROR IN DEBUG CONSOLE:
--------------------------------
```
> ════════ Exception caught by gesture library
> ═══════════════════════════════════ The following assertion was thrown
> while dispatching a pointer event:
> 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line
> 377 pos 12: '_initialButtons == kPrimaryButton': is not true.
> 
> When the exception was thrown, this was the stack
> #2 DragGestureRecognizer._checkStart package:flutter/…/gestures/monodrag.dart:377
> #3 DragGestureRecognizer.acceptGesture package:flutter/…/gestures/monodrag.dart:308
> #4 GestureArenaManager.sweep package:flutter/…/gestures/arena.dart:156
> #5 GestureBinding.handleEvent package:flutter/…/gestures/binding.dart:222
> #6 GestureBinding.dispatchEvent package:flutter/…/gestures/binding.dart:198 ...
> 
> Event: PointerUpEvent#ea064(position: Offset(131.3, 311.7)) position:
> Offset(131.3, 311.7) Target: <WidgetsFlutterBinding>
> ══════════════════════════════════════════════════════════════════
```

CODE SNIPPET:
----------------
```
import 'package:flutter/material.dart';
import 'package:carousel_slider/carousel_slider.dart';

Widget carouselSliderDemo() {
return CarouselSlider.builder(
itemCount: 5,
options: CarouselOptions(
autoPlay: false,
enableInfiniteScroll: false,
enlargeCenterPage: false,
scrollDirection: Axis.horizontal,
viewportFraction: 1.0,
),
itemBuilder: (context, index) {
    return Container(
        child: Image.network(
          'https://images.pexels.com/photos/672657/pexels-photo-672657.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          fit: BoxFit.cover,
          width: MediaQuery.of(context).size.width,
        ),
      );
 });
}
```

Pubspec.yaml Dependency:
------------------------------
`carousel_slider: ^2.2.1`

**Comment by DesmondFox** [comment]
Same problem

**Comment by yourshinsuke** [comment]
same problem

**Comment by yourshinsuke** [comment]
Two fingers on the carousel image cause an issue #166

**Comment by yourshinsuke** [comment]
I am annoying the error. so I replaced other one.
```
flutter_carousel_slider: ^1.0.1
```

**Comment by 0100101101001011** [comment]
Same problem here. Is there a fix yet?
