### ISSUE TITLE
positions.isNotEmpty error on sliding

### ISSUE THREAD

**Issue by govindmaheshwari2** [serenader2014/flutter_carousel_slider#200]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 182 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
E/flutter (21043): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (21043): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (21043): #2      PageController.page (package:flutter/src/widgets/page_view.dart:182:7)
E/flutter (21043): #3      CarouselSliderState.getTimer.<anonymous closure> (package:carousel_slider/carousel_slider.dart:111:57)
E/flutter (21043): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (21043): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21043): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21043): #7      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1042:26)
E/flutter (21043): #8      _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (21043): #9      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21043): #10     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1026:26)
E/flutter (21043): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (21043): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (21043): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (21043): 
W/System  (21043): A resource failed to call close.

**Comment by matheusoliveira-vwi** [comment]
Did you find the solution?

**Comment by matheusoliveira-vwi** [comment]
I managed to correct it in my case, share the code snippet, so I can try to help
