### ISSUE TITLE
Memory leak with image on carousel_slider

### ISSUE THREAD

**Issue by sirajulhudalabs** [serenader2014/flutter_carousel_slider#218]
My application stops working when the package is using with image
My stack trace is:

```D/AndroidRuntime(18441): Shutting down VM
E/AndroidRuntime(18441): FATAL EXCEPTION: main
E/AndroidRuntime(18441): Process: com.sirajulhuda.app, PID: 18441
E/AndroidRuntime(18441): java.lang.RuntimeException: Internal error in Cloud Firestore (21.4.3).
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(com.google.firebase:firebase-firestore@@21.4.3:534)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:2)
E/AndroidRuntime(18441): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(18441): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(18441): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(18441): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(18441): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18441): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(18441): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(18441): Caused by: java.lang.RuntimeException: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.sirajulhuda.app/databases/firestore.%5BDEFAULT%5D.sirajulhudaapp.%28default%29' of size 4194304 due to error -12.
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.4.3:325)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(Unknown Source:4)
E/AndroidRuntime(18441): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime(18441): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(18441): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@21.4.3:229)
E/AndroidRuntime(18441): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(18441): Caused by: android.database.CursorWindowAllocationException: Could not allocate CursorWindow '/data/user/0/com.sirajulhuda.app/databases/firestore.%5BDEFAULT%5D.sirajulhudaapp.%28default%29' of size 4194304 due to error -12.
E/AndroidRuntime(18441): 	at android.database.CursorWindow.nativeCreate(Native Method)
E/AndroidRuntime(18441): 	at android.database.CursorWindow.<init>(CursorWindow.java:145)
E/AndroidRuntime(18441): 	at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:319)
E/AndroidRuntime(18441): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:159)
E/AndroidRuntime(18441): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:152)
E/AndroidRuntime(18441): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
E/AndroidRuntime(18441): 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.local.SQLitePersistence$Query.forEach(com.google.firebase:firebase-firestore@@21.4.3:463)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.local.SQLiteTargetCache.getTargetData(com.google.firebase:firebase-firestore@@21.4.3:218)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.local.LocalStore.allocateTarget(com.google.firebase:firebase-firestore@@21.4.3:534)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.core.SyncEngine.listen(com.google.firebase:firebase-firestore@@21.4.3:196)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.core.EventManager.addQueryListener(com.google.firebase:firebase-firestore@@21.4.3:104)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$listen$6(com.google.firebase:firebase-firestore@@21.4.3:170)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(Unknown Source:4)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(com.google.firebase:firebase-firestore@@21.4.3:436)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(Unknown Source:2)
E/AndroidRuntime(18441): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(com.google.firebase:firebase-firestore@@21.4.3:322)
E/AndroidRuntime(18441): 	... 8 more
W/Firestore(18441): (21.4.3) [AsyncQueue]: Refused to enqueue task after panic
W/libc    (18441): pthread_create failed: couldn't allocate 1085440-bytes mapped space: Out of memory
W/sirajulhuda.ap(18441): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
W/sirajulhuda.ap(18441): Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again" (VmSize 4184064 kB)
W/libc    (18441): pthread_create failed: couldn't allocate 1085440-bytes mapped space: Out of memory
W/sirajulhuda.ap(18441): Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Try again" (VmSize 4184064 kB)
E/AndroidRuntime(18441): FATAL EXCEPTION: pool-10-thread-2
E/AndroidRuntime(18441): Process: com.sirajulhuda.app, PID: 18441
E/AndroidRuntime(18441): java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
E/AndroidRuntime(18441): 	at java.lang.Thread.nativeCreate(Native Method)
E/AndroidRuntime(18441): 	at java.lang.Thread.start(Thread.java:883)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1043)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1185)
E/AndroidRuntime(18441): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(18441): 	at java.lang.Thread.run(Thread.java:919)
I/sirajulhuda.ap(18441): Background concurrent copying GC freed 78372(4548KB) AllocSpace objects, 0(0B) LOS objects, 45% free, 28MB/52MB, paused 2.132ms total 314.375ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4722688, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 279168(13MB) AllocSpace objects, 7(2312KB) LOS objects, 49% free, 19MB/38MB, paused 2.084ms total 286.704ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4722688, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 98325(3888KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 15MB/30MB, paused 1.778ms total 232.581ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4722688, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4722688, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Forcing collection of SoftReferences for 4608KB allocation
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 18781(719KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 14MB/29MB, paused 1.796ms total 269.769ms
I/sirajulhuda.ap(18441): WaitForGcToComplete blocked HeapTrim on HeapTrim for 125.580ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4722688, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Throwing OutOfMemoryError "Failed to allocate a 4718600 byte allocation with 15287094 free bytes and 177MB until OOM, target footprint 30574190, growth limit 201326592" (VmSize 4179368 kB)
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 9441280, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 82918(1599KB) AllocSpace objects, 1(2308KB) LOS objects, 49% free, 17MB/34MB, paused 1.651ms total 207.077ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 9441280, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 6(16KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 17MB/34MB, paused 1.652ms total 206.429ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 9441280, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 9441280, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Forcing collection of SoftReferences for 9216KB allocation
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 47(17KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 17MB/34MB, paused 1.646ms total 265.294ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 9441280, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Throwing OutOfMemoryError "Failed to allocate a 9437192 byte allocation with 17903343 free bytes and 174MB until OOM, target footprint 35806687, growth limit 201326592" (VmSize 4177060 kB)
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 8404992, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 129325(7327KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 21MB/43MB, paused 1.662ms total 209.326ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 8404992, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 1(15KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 21MB/43MB, paused 1.696ms total 206.819ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 8404992, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 8404992, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Forcing collection of SoftReferences for 8205KB allocation
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Alloc concurrent copying GC freed 18(16KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 21MB/43MB, paused 1.696ms total 273.757ms
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 8404992, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
W/sirajulhuda.ap(18441): Throwing OutOfMemoryError "Failed to allocate a 8402552 byte allocation with 22621677 free bytes and 170MB until OOM, target footprint 45243357, growth limit 201326592" (VmSize 4177060 kB)
W/sirajulhuda.ap(18441): Long monitor contention with owner main (18441) at void sun.misc.Unsafe.park(boolean, long)(Unsafe.java:-2) waiters=0 in void com.google.firebase.crashlytics.internal.common.CrashlyticsController.handleUncaughtException(com.google.firebase.crashlytics.internal.settings.SettingsDataProvider, java.lang.Thread, java.lang.Throwable) for 3.978s
W/sirajulhuda.ap(18441): Large object allocation failed: Failed anonymous mmap(0x0, 4202496, 0x3, 0x22, -1, 0): Out of memory. See process maps in the log.
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/sirajulhuda.ap(18441): Starting a blocking GC Alloc
I/Process (18441): Sending signal. PID: 18441 SIG: 9
Lost connection to device.```

**Comment by sirajulhudalabs** [comment]
after a little research i finds it's not by library. I closes this.
