### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by volgin** [serenader2014/flutter_carousel_slider#229]
This is from an automated error report from one of our users. I don't know what actions led to this exception.

```
monodrag.dart in DragGestureRecognizer.acceptGesture at line 324
carousel_slider.dart in _MultipleGestureRecognizer.rejectGesture at line 336
arena.dart in GestureArenaManager.sweep at line 160

```
I hope this is enough information to figure out what causes it.

**Comment by kanhaiyhacker** [comment]
I am also facing the same issue. 

The following _CastError was thrown building AnimatedBuilder(animation: PageController#a54d1(one client, offset 3600000.0), dirty, state: _AnimatedState#c1ea5):
Null check operator used on a null value

The relevant error-causing widget was: 
  CarouselSlider file:///D:/external%20projects/MVSCCs/MVSCCS_APP/lib/src/widgets/HomeSliderWidget.dart:38:15
When the exception was thrown, this was the stack: 
#0      _CarouselSliderState.build.<anonymous closure>.<anonymous closure> (package:carousel_slider/carousel_slider.dart:159:38)
#1      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1483:19)
#2      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:179:48)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4758:27)
#4

**Comment by waqaskhan409** [comment]
I'm also facing the same issue...
The following _CastError was thrown building AnimatedBuilder(animation: PageController#c7a83(one client, offset 1803636.4), dirty, state: _AnimatedState#cfddc):
Null check operator used on a null value

**Comment by waqaskhan409** [comment]
My error was gone by using the updated package carousel_slider: ^2.3.1. May be by updating the package will solve your problem.

**Comment by volgin** [comment]
I am using the latest version, and still see this error. It does not happen often, but it still happens.

**Comment by nehal076** [comment]
I am also facing this issue. Please provide a solution

**Comment by HarisAtiq2762** [comment]
same here, I am also facing this issue

**Comment by carlhung** [comment]
so am I. haha

**Comment by hamidamazai** [comment]
Run the following commands in terminal 
flutter channel stable
flutter upgrade

**Comment by jlnrrg** [comment]
<details><summary>I am up to date</summary>

```
Flutter is already up to date on channel stable
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (12 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```
</details>
This is a combination of two packages, so I am not certain this fits purely flutter_carousel. But I encountered the error in it's code, so pretty certain.

<details><summary>my code</summary>

```dart

import 'package:smooth_page_indicator/smooth_page_indicator.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:carousel_slider/carousel_controller.dart';
import 'package:carousel_slider/carousel_slider.dart';
.
.
.

  @override
  Widget build(BuildContext context) {
    final ValueNotifier<int> activeIndex = useState(0);
    final CarouselController _controller = CarouselController();

return Column(
      children: [
        CarouselSlider.builder(
            itemCount: groupedStyles.length,
            options: CarouselOptions(
                height: 400,
                // viewportFraction: 1.0,
                enableInfiniteScroll: false,
                onPageChanged: (int index, _) => activeIndex.value = index),
            itemBuilder: (_, int index, int realIndex) {
              return Container(height: 100, width: 100, color: Colors.red);
            }),
        AnimatedSmoothIndicator(
            activeIndex: activeIndex.value,
            count: groupedStyles.length,
            effect: const WormEffect(),
            onDotClicked: (int index) async {
              debugPrint(index.toString());
              await _controller.animateToPage(index);
            })
      ],
    );
}
```
</details>

The problem seems to be here: (_state is null, but forced to be not)

<details><summary>flutter_carousel_slider code</summary>

```dart
class CarouselControllerImpl implements CarouselController {

  CarouselState? _state;
.
.
.
  Future<void> animateToPage(int page,
      {Duration? duration = const Duration(milliseconds: 300),
      Curve? curve = Curves.linear}) async {
    final bool isNeedResetTimer = _state!.options.pauseAutoPlayOnManualNavigate; // <-- state is null
    if (isNeedResetTimer) {
      _state!.onResetTimer();
    }
    final index = getRealIndex(_state!.pageController!.page!.toInt(),
        _state!.realPage - _state!.initialPage, _state!.itemCount);
    _setModeController();
    await _state!.pageController!.animateToPage(
        _state!.pageController!.page!.toInt() + page - index,
        duration: duration!,
        curve: curve!);
    if (isNeedResetTimer) {
      _state!.onResumeTimer();
    }
  }
```
</details>

**Comment by diyarfaraj** [comment]
having same problem here. Any solution anyone?

**Comment by omidraha** [comment]
Same issue.
Related:
https://github.com/flutter/flutter/issues/66250
https://stackoverflow.com/questions/64822800/null-check-operator-used-on-a-null-value-carousel-flutter

**Comment by viciainc** [comment]
This worked for me

So I edited scrollposition.dart package

from line 133
@override
//double get minScrollExtent => _minScrollExtent!;
// double? _minScrollExtent;
double get minScrollExtent {
if (_minScrollExtent == null) {
_minScrollExtent = 0.0;
}
return double.parse(_minScrollExtent.toString());
}

double? _minScrollExtent;

@override
// double get maxScrollExtent => _maxScrollExtent!;
// double? _maxScrollExtent;
double get maxScrollExtent {
if (_maxScrollExtent == null) {
_maxScrollExtent = 0.0;
}
return double.parse(_maxScrollExtent.toString());
}

double? _maxScrollExtent;

**Comment by hamid1245** [comment]
also facing the same issue

**Comment by JuanSuarezZ** [comment]
the same issue

**Comment by Stewioie** [comment]
Still active in 2.10.4

```
I/flutter ( 5039): Null check operator used on a null value
I/flutter ( 5039): #0      ScrollPosition.maxScrollExtent (package:flutter/src/widgets/scroll_position.dart:143:49)
```

flutter doctor

```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-arm, locale hu-HU)
    • Flutter version 2.10.4 at /Users/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/Work/AndroidSDK
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by rihemebh** [comment]
I am facing the same issue here and I am using the latest version
is there any update ? 

![image](https://user-images.githubusercontent.com/33090727/222971425-a19be735-e122-499d-bb70-56e27c64cb2d.png)

**Comment by hrajwade96** [comment]
Facing this same crash issue in prod version of our project, events count is also quite high :

**Logs :**
```
String: Null check operator used on a null value
  File "carousel_slider.dart", line 144, in CarouselSliderState.getTimer.<fn>
  File "timer_impl.dart", line 398, in _Timer._runTimers
  File "timer_impl.dart", line 429, in _Timer._handleMessage
  File "isolate_patch.dart", line 184, in _RawReceivePort._handleMessage
```

@serenader2014  can you help in this?

Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (8 months ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1

**Comment by kishan-dhankecha** [comment]
This is fixed in the fork here https://pub.dev/packages/carousel_slider_plus. See [#f7f6183](https://github.com/kishan-dhankecha/carousel_slider_plus/commit/f7f6183).
