### ISSUE TITLE
Assertion was thrown during performLayout()

### ISSUE THREAD

**Issue by jithware** [serenader2014/flutter_carousel_slider#332]
```══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 270 pos 12:
'firstIndex == 0 || childScrollOffset(firstChild!)! - scrollOffset <= precisionErrorTolerance': is
not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  PageView
  PageView:file:///home/.../flutter/.pub-cache/hosted/pub.dartlang.org/carousel_slider-4.0.0/lib/carousel_slider.dart:266:39

When the exception was thrown, this was the stack:
#2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:270:12)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#30     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:277:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#36     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:233:12)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#42     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:487:13)
#43     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
#44     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:281:12)
#45     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#46     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#47     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:371:11)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#49     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#50     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#51     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#62     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#68     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#71     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#72     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#73     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005:7)
#74     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#75     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#80     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#81     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#82     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#83     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#87     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#89     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#93     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#98     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3426:14)
#99     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#101    RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#102    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#103    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#104    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#105    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#106    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#107    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#108    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#109    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#110    LiveTestWidgetsFlutterBinding.handleDrawFrame (package:flutter_test/src/binding.dart:1450:13)
#111    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#115    _invoke (dart:ui/hooks.dart:150:10)
#116    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#117    _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)

The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#8f6f6 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
    Viewport ← IgnorePointer-[GlobalKey#9b1c9] ← Semantics ← Listener ← _GestureSemantics ←
    RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#07d3d] ← Listener ← _ScrollableScope
    ← _ScrollSemantics-[GlobalKey#14e7e] ← ⋯
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
    scrollOffset: 783843.2, remainingPaintExtent: 392.0, crossAxisExtent: 50.0, crossAxisDirection:
    AxisDirection.down, viewportMainAxisExtent: 392.0, remainingCacheExtent: 392.0, cacheOrigin: 0.0)
  geometry: null
  currently live children: 9998 to 10002
This RenderObject had the following descendants (showing up to depth 5):
    child with index 9998: RenderIndexedSemantics#6c015 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child: RenderRepaintBoundary#49b33 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderPositionedBox#bf560 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
```

**Comment by jithware** [comment]
Decided to create a custom carousel instead. For a good example see:

https://gist.github.com/IshanFx/48d64b08c5d66eae4b42484c20fc9280

**Comment by paplorinc** [comment]
I'm still getting this ...

**Comment by IgordeOliveira** [comment]
I`m with the same issue, I notice that happens only with infiniteScroll enabled
