### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by SYND-GITHUB** [serenader2014/flutter_carousel_slider#358]
E/flutter (27320): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (27320): #0      CarouselSliderState.getTimer.<anonymous closure> (package:carousel_slider/carousel_slider.dart:135:63)
E/flutter (27320): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (27320): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (27320): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (27320): #4      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281:26)
E/flutter (27320): #5      _rootRunUnary (dart:async/zone.dart:1442:13)
E/flutter (27320): #6      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (27320): #7      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1265:26)
E/flutter (27320): #8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (27320): #9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (27320): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by Nigmatulin8** [comment]
If you try to use something like animateToPage etc. you can try it
https://stackoverflow.com/questions/64822800/null-check-operator-used-on-a-null-value-carousel-flutter

**Comment by masumeZarepur** [comment]
I have same problem .what did you do to solve this problem ??

**Comment by Nigmatulin8** [comment]
> I have same problem .what did you do to solve this problem ??

Try to put initialization the carouselController inside the initState method.

This is my case
```
class _PlansPageState extends State<PlansPage> {
    int _currentPage = 1;

    late CarouselController carouselController;

    @override
    void initState() {
        super.initState();
        carouselController = CarouselController();
     }
}
```
Then I was able to use 
`carouselController.animateToPage(_currentPage);` in onTap inside GestureDetector

**Comment by rensvis** [comment]
I had the same issues because I forgot to add the `carouselController` to the `CarouselSlider`:

`
CarouselSlider.builder(
  carouselController: carouselController,
  ...
`

**Comment by heshesh2010** [comment]
+1

**Comment by yuyangkk** [comment]
The same problem. Does anyone have a solution?

**Comment by sfx2k** [comment]
The trick is to initialize the CarouselSliderController outside the Build method!
